import Head from "next/head";
import Image from "next/image";
import iag from "../../public/2.jpg";
import { useRouter } from "next/router";
import { database } from "../../utils/firebaseConfig";
import { useEffect, useState } from "react";
import { doc, getDoc } from "firebase/firestore";

const ItemPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const [title, setTitle] = useState("");
  const [desc, setDesc] = useState("");
  const [price, setPrice] = useState("");

  useEffect(() => {
    const docRef = doc(database, "products", `${id}`);

    getDoc(docRef).then((docSnap) => {
      if (docSnap.exists()) {
        const data = docSnap.data();
        setTitle(data.title);
        setDesc(data.desc);
        setPrice(data.price);
      } else {
        console.log("h");
      }
    });
  }, []);

  return (
    <div>
      <Head>
        <title>{id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-full h-screen absolute top-0 left-0 mb-4">
        <div className="w-full h-full relative px-4 py-2">
          <div className="mt-32">
            <h1 className=" text-7xl capitalize inline-block relative">
              {title}
              <p className="text-sm font-light absolute top-0 right-0 translate-x-full">
                (${price})
              </p>
            </h1>
            <p className="text-2xl mt-2 w-1/2">{desc}</p>
            <button>Pay ${price}</button>
          </div>
          <div className="mt-32"></div>
          <div className="w-full">
            <div className="w-1/2 ml-auto relative">
              <Image src={iag} className="w-full object-cover" alt="hey" />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default ItemPage;
