import Head from "next/head";
import Link from "next/link";

const About = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-full px-4 absolute bottom-0  pb-2">
        <p className="text-2xl">
          Kinka is a creative developer designing daily, exploring old and new
          art experiences. In the heart of Malaga, filled with vibrant cultures
          and the joyful spirit from the locals, creativity is never lacking. My
          experiences are tied to graphic design, posters and others. The work
          of Kinka, young artist from Malaga is a diligent quest of temporality
          and beauty. The artist's ongoing interest in pictorial aesthetics is
          shown throughout his technique with print. His work explores themes of
          how the human communicates with idealogies of the occurences in the
          world. Kinka's designs created over the last years have received
          significant attention across the digital design industry.
        </p>
        <section className="w-full mt-4 pb-2 flex">
          <Link href={""}>
            <h1 className="text-base uppercase">Instagram</h1>
          </Link>
          <Link href={""} className="ml-4">
            <h1 className="text-base uppercase">Facebook</h1>
          </Link>
          <Link href={""} className="ml-4">
            <h1 className="text-base uppercase">Twitter</h1>
          </Link>
          <Link href={""} className="ml-4">
            <h1 className="text-base uppercase">Dribbble</h1>
          </Link>
        </section>
      </section>
    </div>
  );
};

export default About;
