import Head from "next/head";
import React, { useState } from "react";
import { useRouter } from "next/router";
import { motion as m } from "framer-motion";
// import video from "../public/video.mp4";

export default function Home() {
  const router = useRouter();
  const [headerss, setHeaders] = useState([]);

  const handleClick = (e) => {
    setHeaders([...headerss, { x: e.clientX, y: e.clientY }]);
  };

  const redirectRoute = () => {
    router.push("/projects");
  };

  return (
    <m.div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-full h-screen absolute left-0 top-0  overflow-hidden flex justify-center items-center">
        {/* <div className="w-full h-full relative" onClick={handleClick}>
          {headerss.map((header) =>
            React.createElement(
              "div",
              {
                className: `text-lg absolute h-96 w-96 rounded-sm bg-orange-600 border border-black`,
                style: { left: `${header.x}px`, top: `${header.y}px` },
                key: `${header.x}`,
              },
              `(${header.x}, ${header.y})`
            )
          )}
        </div> */}

        <video
          className="w-full h-full object-cover"
          autoPlay
          loop
          onClick={redirectRoute}
        >
          <source src="./video.mp4" type="video/mp4" />
        </video>
      </section>
    </m.div>
  );
}
