import Head from "next/head";
import React, { useState } from "react";

export default function Home() {
  const [headerss, setHeaders] = useState([]);

  const handleClick = (e) => {
    setHeaders([...headerss, { x: e.clientX, y: e.clientY }]);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-full h-screen absolute left-0 top-0  overflow-hidden flex justify-center items-center">
        <div className="w-full h-full relative" onClick={handleClick}>
          {headerss.map((header) =>
            React.createElement(
              "div",
              {
                className: `text-lg absolute h-96 w-96 rounded-sm bg-orange-600 border border-black`,
                style: { left: `${header.x}px`, top: `${header.y}px` },
                key: `${header.x}`,
              },
              `(${header.x}, ${header.y})`
            )
          )}
        </div>
      </section>
    </div>
  );
}
