import Head from "next/head";
import { motion as m } from "framer-motion";
import Image from "next/image";

const Projects = () => {
  return (
    <m.div
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      exit={{ opacity: 1 }}
    >
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="w-full px-4 py-2 mt-12 flex gap-x-8 gap-y-24 flex-wrap">
        <div className="w-48 h-48 bg-black relative hover:grayscale">
          <Image
            src="/2.jpg"
            fill={true}
            className="w-full h-full object-cover"
            alt="heyy"
          />
        </div>
      </section>
    </m.div>
  );
};

export default Projects;
